# Boiler plate for github action to run on main branch and every push
name: Build and Deploy
on:
    push:
        branches:
            - main
jobs:
    build_and_push_docker_image:
        runs-on: ubuntu-latest
        steps:
          - name: Check out repository code
            uses: actions/checkout@v4
    
          - name: Login to self hosted registry
            uses: docker/login-action@v3
            with:
              registry: https://registry.studien.us
              username: ${{ secrets.REGISTRY_USERNAME }}
              password: ${{ secrets.REGISTRY_PASSWORD }} 

          - name: Build .env file in root directory
            env:
              REACT_APP_GOOGLE_OAUTH_CLIENT_ID: ${{ secrets.REACT_APP_GOOGLE_OAUTH_CLIENT_ID }}
            run: |
                echo "REACT_APP_GOOGLE_OAUTH_CLIENT_ID=$REACT_APP_GOOGLE_OAUTH_CLIENT_ID" > ".env"

          - name: Build and push docker image
            run: |
              docker buildx build --platform linux/amd64 -t lifecounter .
              docker tag docker.io/library/lifecounter registry.studien.us/lifecounter
              docker push registry.studien.us/lifecounter          
    