name: Run jest tests
on: [push]
jobs:
  jest-test:
    steps:
      runs-on: ubuntu-latest
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Runs npm install
        run: npm install

      - name: Runs test
        run: npm test

