name: Run jest tests
on: [push]
jobs:
  jest-test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Runs npm install
        run: npm install

      - name: Runs test
        run: npm test
  build_and_push_docker_image:
    needs: jest-test
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Login to self hosted registry
        uses: docker/login-action@v3
        with:
          registry: https://registry.studien.us
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }} 

      - name: Build and push docker image
        run: |
          docker buildx build --platform linux/amd64 -t lifecounter .
          docker tag docker.io/library/lifecounter registry.studien.us/lifecounter
          docker push registry.studien.us/lifecounter          



